---
- hosts: app
  tasks:
   - name: upgrade all packages
     yum: name=* state=latest
     become: yes

   - name: Install Docker
     yum: pkg=docker state=installed update_cache=true
     become: yes
     notify:
      - Start Docker

   - name: Install docker-py
     become: yes
     pip:
       name: docker-py
       state: latest

   - name: Restart Docker
     service: name=docker state=restarted
     become: yes

   - name: Pull default Docker image
     become: yes
     docker_image:
       name: "bkimminich/juice-shop"
       source: pull

   - name: Create application containers
     become: yes
     docker_container:
       name: "juice-shop"
       image: "bkimminich/juice-shop"
       detach: true
       ports:
         - "3000:3000"
       state: started


  handlers:
   - name: Start Docker
     service: name=docker state=started
     become: yes
